[toolchain]

[features]
seeds = true
skip-lint = false

[programs.localnet]
counter = "6YKvBAKt9BrWicEit9EW8EWknKawy4s1Mr2qTc1gnupW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/whitehorse/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
